language: node_js
node_js:
    - "node"
    - "6"
    - "6.1"
    - "5.1"
    - "4.0"

install:
    - npm install -g typescript
    - npm install -g mocha
    - npm install -g typings
    - typings install
    - npm install